"use client";
import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { Building2,ChevronDown,Globe2,Home,Languages,LayoutDashboard,LockKeyhole,MapPin,Menu,Plus,Search,Settings,Users } from "lucide-react";
import type { PropertyCardData } from "@/lib/api";

const nav=[[LayoutDashboard,"Dashboard"],[Home,"Properties"],[Building2,"Projects"],[MapPin,"Locations"],[Languages,"Languages"],[Users,"Users"],[Settings,"Site settings"]] as const;

export default function Admin() {
  const [active,setActive]=useState("Dashboard");
  const [auth,setAuth]=useState<"loading"|"in"|"out">("loading");
  const [error,setError]=useState("");
  const [properties,setProperties]=useState<PropertyCardData[]>([]);
  useEffect(()=>{fetch("/api/admin/auth/me",{credentials:"include"}).then(r=>{const signedIn=r.ok;setAuth(signedIn?"in":"out");if(signedIn)fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080"}/api/public/properties?locale=en`).then(x=>x.ok?x.json():[]).then(setProperties);}).catch(()=>setAuth("out"));},[]);
  async function login(e:FormEvent<HTMLFormElement>) { e.preventDefault();setError("");const data=new FormData(e.currentTarget);const response=await fetch("/api/admin/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({email:data.get("email"),password:data.get("password")})});if(response.ok){setAuth("in");location.reload();}else setError("Unable to sign in. Check your credentials and try again."); }
  if(auth!=="in") return <main className="admin-login"><form onSubmit={login}><Link className="admin-brand" href="/en"><strong>NUVEXA</strong><small>ADMINISTRATION</small></Link><div className="login-mark"><LockKeyhole/></div><h1>{auth==="loading"?"Checking your session":"Welcome back"}</h1><p>{auth==="loading"?"Please wait…":"Sign in with your administrator account."}</p>{auth==="out"&&<><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<span className="login-error">{error}</span>}<button type="submit">Sign in securely</button></>}</form></main>;
  const available=properties.filter(p=>p.status==="Available").length;
  return <main className="admin-shell" dir="ltr"><aside className="admin-sidebar"><Link className="admin-brand" href="/en"><strong>NUVEXA</strong><small>ADMINISTRATION</small></Link><nav>{nav.map(([Icon,label])=><button key={label} className={active===label?"active":""} onClick={()=>setActive(label)}><Icon/>{label}</button>)}</nav><div className="admin-user"><span>ME</span><div><strong>Administrator</strong><small>Authorized user</small></div><ChevronDown/></div></aside><section className="admin-main"><header><button className="admin-menu"><Menu/></button><div><Search/><input placeholder="Search anything..."/></div><Link href="/en" target="_blank"><Globe2/> View website</Link></header><div className="admin-content"><div className="admin-title"><div><p>OVERVIEW</p><h1>{active}</h1></div><button><Plus/> Add property</button></div>{active==="Dashboard"?<><div className="stat-grid">{[["Total properties",properties.length,"Live database"],["Published",properties.length,"Public inventory"],["Available",available,"Ready for sale"]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></article>)}</div><div className="admin-panels"><section><div className="panel-title"><h2>Recent properties</h2><button>View all</button></div><table><thead><tr><th>PROPERTY</th><th>LOCATION</th><th>PRICE</th><th>STATUS</th></tr></thead><tbody>{properties.map(p=><tr key={p.slug}><td><img src={p.coverImage || "/placeholder-property.svg"} alt=""/><div><strong>{p.title}</strong><small>{p.referenceNumber}</small></div></td><td>{p.location}</td><td>{new Intl.NumberFormat("en-EG",{style:"currency",currency:p.currency,maximumFractionDigits:0}).format(p.price)}</td><td><span className="status">{p.status}</span></td></tr>)}</tbody></table></section></div></>:<div className="module-placeholder"><div><Home/><h2>{active} workspace</h2><p>This module uses protected ASP.NET Core admin endpoints.</p><button><Plus/> Create new</button></div></div>}</div></section></main>;
}
